improve handling of LD_LIBRARY_PATH
git-svn-id: svn://svn.macaulay2.com/Macaulay2/trunk@3755 a8012f80-5f13-0410-8dc0-eb77bd940c0d

diff --git a/M2/Macaulay2/bin/M2-load-libs b/M2/Macaulay2/bin/M2-load-libs
--- a/M2/Macaulay2/bin/M2-load-libs
+++ b/M2/Macaulay2/bin/M2-load-libs
@@ -1,20 +1,22 @@
-#! /bin/sh
+#! /bin/bash
 
 if ! type -p M2 >/dev/null
 then echo 'M2 not found on path' >&2
      exit 1
 fi
 
-NEWLIB="$(dirname $(dirname $(type -p M2)))/lib"
+BINDIR=$(dirname $(type -p M2))
+M2DIR=$(cd "$BINDIR"/..; /bin/pwd)
+LIBDIR=$M2DIR/lib
 
-if ! [ -d "$NEWLIB" ]
-then echo "directory $NEWLIB not found" >&2
+if ! [ -d "$LIBDIR" ]
+then echo "directory $LIBDIR not found" >&2
      exit 1
 fi
 
 if [ -f /etc/ld.so.conf ]
-then OLIBS=`cat /etc/ld.so.conf | xargs echo | sed 's/ /:/g'`
+then OLIBS=$(echo $(</etc/ld.so.conf) | sed 's/ /:/g')
 fi
 
-export LD_LIBRARY_PATH="/usr/lib:/lib:/usr/local/lib:$OLIBS:$NEWLIB" 
+export LD_LIBRARY_PATH="/usr/lib:/lib:/usr/local/lib:$OLIBS:$LIBDIR" 
 exec M2 "$@"
