fix real and complex numbers
git-svn-id: svn://svn.macaulay2.com/Macaulay2/trunk/M2@6226 a8012f80-5f13-0410-8dc0-eb77bd940c0d

diff --git a/Macaulay2/packages/Macaulay2/test/Makefile.test.in b/Macaulay2/packages/Macaulay2/test/Makefile.test.in
--- a/Macaulay2/packages/Macaulay2/test/Makefile.test.in
+++ b/Macaulay2/packages/Macaulay2/test/Makefile.test.in
@@ -44,8 +44,8 @@ status :: $(TESTFILES)
 		   time $(DOTS)/bin/M2@EXE@ $(ARGS) >>$*.errors 2>&1 ; \
 		then mv $*.errors $@ ; \
 		else a=$$?; \
-		     echo "$*.errors:0: error output left here; some errors follow" >&2 ; \
 		     <$*.errors $(FILTER) ; \
+		     echo "$*.errors:0: error output left here for the errors above:" >&2 ; \
 		     exit $$a ; \
 		fi
 %.out : %.m2-input
