*** empty log message ***
git-svn-id: svn://svn.macaulay2.com/Macaulay2/trunk/M2@1474 a8012f80-5f13-0410-8dc0-eb77bd940c0d

diff --git a/bin/M2-help.in b/bin/M2-help.in
--- a/bin/M2-help.in
+++ b/bin/M2-help.in
@@ -1,6 +1,14 @@
 #! /bin/sh
 PREFIX=@prefix@
-M2DOC="$PREFIX/share/doc/Macaulay2/index.html"
+M2DIR="$PREFIX/share/doc/Macaulay2"
+M2DOC="$M2DIR/index.html"
+if [ ! -f "$M2DOC" ]
+then M2DOC="$M2DIR/@PACKAGE_VERSION@/html/index.html"
+fi
+if [ ! -f "$M2DOC" ]
+then echo "Macaulay 2 documentation not found." >&2
+     exit 1
+fi
 if   [ "$WWWBROWSER" ]
 then "$WWWBROWSER" "$M2DOC"
 elif [ `uname -s` = Darwin ]
