update debian stuff
git-svn-id: svn://svn.macaulay2.com/Macaulay2/trunk@4621 a8012f80-5f13-0410-8dc0-eb77bd940c0d

diff --git a/M2/debian/postinst.in b/M2/debian/postinst.in
--- a/M2/debian/postinst.in
+++ b/M2/debian/postinst.in
@@ -1,12 +1,27 @@
 #!/bin/sh
-set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 case "$1" in
     configure)
 	/usr/bin/M2 --dumpdata
-        ;;
+    ;;
+
     abort-upgrade|abort-remove|abort-deconfigure)
-	;;
+
+    ;;
+
     *)
-	echo "postinst called with unknown argument \`$1'" >&2
-	;;
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
 esac
