*** empty log message ***
git-svn-id: svn://svn.macaulay2.com/Macaulay2/trunk/M2@1068 a8012f80-5f13-0410-8dc0-eb77bd940c0d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2905,9 +2905,9 @@ EOF
 
 ac_config_headers="$ac_config_headers include/config.h"
 
-CONFIGURED_FILES="config.Makefile Makefile Macaulay2/Makefile Macaulay2/m2/Makefile Macaulay2/basictests/Makefile Macaulay2/book/Makefile Macaulay2/c/Makefile Macaulay2/d/Makefile Macaulay2/dumpdata/Makefile Macaulay2/e/Makefile Macaulay2/emacs/Makefile Macaulay2/html/Makefile Macaulay2/packages/Makefile Macaulay2/packages/ComputationsBook/Makefile Macaulay2/test/Makefile Macaulay2/tutorial/Makefile Macaulay2/setup Macaulay2/util/Makefile bin/M2 bin/Makefile "
+CONFIGURED_FILES="config.Makefile Makefile Macaulay2/Makefile Macaulay2/m2/Makefile Macaulay2/basictests/Makefile Macaulay2/book/Makefile Macaulay2/c/Makefile Macaulay2/d/Makefile Macaulay2/dumpdata/Makefile Macaulay2/e/Makefile Macaulay2/emacs/Makefile Macaulay2/html/Makefile Macaulay2/packages/Makefile Macaulay2/packages/ComputationsBook/Makefile Macaulay2/test/Makefile Macaulay2/tutorial/Makefile Macaulay2/setup Macaulay2/util/Makefile bin/M2 bin/Makefile encap/Makefile "
 
-ac_config_files="$ac_config_files config.Makefile Makefile Macaulay2/Makefile Macaulay2/m2/Makefile Macaulay2/basictests/Makefile Macaulay2/book/Makefile Macaulay2/c/Makefile Macaulay2/d/Makefile Macaulay2/dumpdata/Makefile Macaulay2/e/Makefile Macaulay2/emacs/Makefile Macaulay2/html/Makefile Macaulay2/packages/Makefile Macaulay2/packages/ComputationsBook/Makefile Macaulay2/test/Makefile Macaulay2/tutorial/Makefile Macaulay2/setup Macaulay2/util/Makefile bin/M2 bin/Makefile"
+ac_config_files="$ac_config_files config.Makefile Makefile Macaulay2/Makefile Macaulay2/m2/Makefile Macaulay2/basictests/Makefile Macaulay2/book/Makefile Macaulay2/c/Makefile Macaulay2/d/Makefile Macaulay2/dumpdata/Makefile Macaulay2/e/Makefile Macaulay2/emacs/Makefile Macaulay2/html/Makefile Macaulay2/packages/Makefile Macaulay2/packages/ComputationsBook/Makefile Macaulay2/test/Makefile Macaulay2/tutorial/Makefile Macaulay2/setup Macaulay2/util/Makefile bin/M2 bin/Makefile encap/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -3234,8 +3234,9 @@ do
   "Macaulay2/util/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/util/Makefile" ;;
   "bin/M2" ) CONFIG_FILES="$CONFIG_FILES bin/M2" ;;
   "bin/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/Makefile" ;;
+  "encap/Makefile" ) CONFIG_FILES="$CONFIG_FILES encap/Makefile" ;;
   "include/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/config.h" ;;
-  *) { { echo "$as_me:3238: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3239: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3472,7 +3473,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3475: creating $ac_file" >&5
+    { echo "$as_me:3476: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3490,7 +3491,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3493: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3494: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3503,7 +3504,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3506: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3507: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3564,7 +3565,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:3567: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:3568: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -3575,7 +3576,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3578: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3579: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3588,7 +3589,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3591: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3592: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3705,7 +3706,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:3708: $ac_file is unchanged" >&5
+      { echo "$as_me:3709: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
