*** empty log message ***
git-svn-id: svn://svn.macaulay2.com/Macaulay2/trunk/M2@996 a8012f80-5f13-0410-8dc0-eb77bd940c0d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2916,9 +2916,9 @@ EOF
 
 ac_config_headers="$ac_config_headers include/config.h"
 
-CONFIGURED_FILES="include(config.files)"
+CONFIGURED_FILES="config.Makefile Makefile-run Macaulay2/Makefile Macaulay2/m2/Makefile Macaulay2/basictests/Makefile Macaulay2/book/Makefile Macaulay2/c/Makefile Macaulay2/c2/Makefile Macaulay2/d/Makefile Macaulay2/dbm/Makefile Macaulay2/dumpdata/Makefile Macaulay2/e/Makefile Macaulay2/emacs/Makefile Macaulay2/html/Makefile Macaulay2/packages/Makefile Macaulay2/packages/ComputationsBook/Makefile Macaulay2/test/Makefile Macaulay2/tutorial/Makefile Macaulay2/setup Macaulay2/util/Makefile "
 
-ac_config_files="$ac_config_files include(config.files)"
+ac_config_files="$ac_config_files config.Makefile Makefile-run Macaulay2/Makefile Macaulay2/m2/Makefile Macaulay2/basictests/Makefile Macaulay2/book/Makefile Macaulay2/c/Makefile Macaulay2/c2/Makefile Macaulay2/d/Makefile Macaulay2/dbm/Makefile Macaulay2/dumpdata/Makefile Macaulay2/e/Makefile Macaulay2/emacs/Makefile Macaulay2/html/Makefile Macaulay2/packages/Makefile Macaulay2/packages/ComputationsBook/Makefile Macaulay2/test/Makefile Macaulay2/tutorial/Makefile Macaulay2/setup Macaulay2/util/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -3225,9 +3225,28 @@ for ac_config_target in $ac_config_targets
 do
   case "$ac_config_target" in
   # Handling of arguments.
-  "include(config.files)" ) CONFIG_FILES="$CONFIG_FILES include(config.files)" ;;
+  "config.Makefile" ) CONFIG_FILES="$CONFIG_FILES config.Makefile" ;;
+  "Makefile-run" ) CONFIG_FILES="$CONFIG_FILES Makefile-run" ;;
+  "Macaulay2/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/Makefile" ;;
+  "Macaulay2/m2/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/m2/Makefile" ;;
+  "Macaulay2/basictests/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/basictests/Makefile" ;;
+  "Macaulay2/book/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/book/Makefile" ;;
+  "Macaulay2/c/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/c/Makefile" ;;
+  "Macaulay2/c2/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/c2/Makefile" ;;
+  "Macaulay2/d/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/d/Makefile" ;;
+  "Macaulay2/dbm/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/dbm/Makefile" ;;
+  "Macaulay2/dumpdata/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/dumpdata/Makefile" ;;
+  "Macaulay2/e/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/e/Makefile" ;;
+  "Macaulay2/emacs/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/emacs/Makefile" ;;
+  "Macaulay2/html/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/html/Makefile" ;;
+  "Macaulay2/packages/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/packages/Makefile" ;;
+  "Macaulay2/packages/ComputationsBook/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/packages/ComputationsBook/Makefile" ;;
+  "Macaulay2/test/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/test/Makefile" ;;
+  "Macaulay2/tutorial/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/tutorial/Makefile" ;;
+  "Macaulay2/setup" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/setup" ;;
+  "Macaulay2/util/Makefile" ) CONFIG_FILES="$CONFIG_FILES Macaulay2/util/Makefile" ;;
   "include/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/config.h" ;;
-  *) { { echo "$as_me:3230: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3249: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3464,7 +3483,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3467: creating $ac_file" >&5
+    { echo "$as_me:3486: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3482,7 +3501,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3485: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3504: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3495,7 +3514,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3498: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3517: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3556,7 +3575,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:3559: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:3578: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -3567,7 +3586,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3570: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3589: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3580,7 +3599,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3583: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3602: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3697,7 +3716,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:3700: $ac_file is unchanged" >&5
+      { echo "$as_me:3719: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
