*** empty log message ***
git-svn-id: svn://svn.macaulay2.com/Macaulay2/trunk/M2@995 a8012f80-5f13-0410-8dc0-eb77bd940c0d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2916,9 +2916,9 @@ EOF
 
 ac_config_headers="$ac_config_headers include/config.h"
 
-CONFIGURED_FILES="`cat config.files`"
+CONFIGURED_FILES="include(config.files)"
 
-ac_config_files="$ac_config_files `cat config.files`"
+ac_config_files="$ac_config_files include(config.files)"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -3225,10 +3225,9 @@ for ac_config_target in $ac_config_targets
 do
   case "$ac_config_target" in
   # Handling of arguments.
-  "`cat" ) CONFIG_FILES="$CONFIG_FILES `cat" ;;
-  "config.files`" ) CONFIG_FILES="$CONFIG_FILES config.files`" ;;
+  "include(config.files)" ) CONFIG_FILES="$CONFIG_FILES include(config.files)" ;;
   "include/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/config.h" ;;
-  *) { { echo "$as_me:3231: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3230: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3465,7 +3464,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3468: creating $ac_file" >&5
+    { echo "$as_me:3467: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3483,7 +3482,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3486: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3485: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3496,7 +3495,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3499: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3498: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3557,7 +3556,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:3560: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:3559: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -3568,7 +3567,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3571: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3570: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3581,7 +3580,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3584: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3583: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3698,7 +3697,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:3701: $ac_file is unchanged" >&5
+      { echo "$as_me:3700: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
