git-svn-id: svn://svn.macaulay2.com/Macaulay2/trunk/M2@4280 a8012f80-5f13-0410-8dc0-eb77bd940c0d

diff --git a/Macaulay2/bin/M2-load-libs b/Macaulay2/bin/M2-load-libs
--- a/Macaulay2/bin/M2-load-libs
+++ b/Macaulay2/bin/M2-load-libs
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 if ! type -p $0 >/dev/null
-then echo '$0 not found on path, something is strange' >&2
+then echo '$0 not found, something is strange' >&2
      exit 1
 fi
 
