Add sha256sum check for downloaded tarballs in the autotools build
This is a standard check for security reasons to make sure we're
installing what we expect to install.  We already do this in the cmake
build, and it's also done for common package managers that download
tarballs during build (e.g., homebrew and spack).

diff --git a/M2/libraries/Makefile.library.in b/M2/libraries/Makefile.library.in
--- a/M2/libraries/Makefile.library.in
+++ b/M2/libraries/Makefile.library.in
@@ -264,6 +264,17 @@ CHECKFETCHED = case "$(URL)" in									\
 	esac
 $(TARFILE_DIR)/$(TARFILE) :
 	(cd $(TARFILE_DIR) && $(FETCHER) $(URL)/$(TARFILE) $(FETCHOPTS) && $(CHECKFETCHED))
+ifneq ($(SHA256SUM), true)
+	@cd $(TARFILE_DIR) && \
+		actual=$$(sha256sum $(TARFILE) | awk '{print $$1}'); \
+		if test "x$(SHA256SUM)" != "x$$actual"; \
+		then echo "error: *** SHA256 hash of $(TARFILE) does not match the expected value"; \
+		echo "  expected: $(SHA256SUM)"; \
+		echo "    actual: $$actual"; \
+		exit 1; \
+		else echo " \033[32m✓\033[0m SHA256 ok ($(SHA256SUM))"; \
+		fi
+endif
 distclean: package-distclean
 clean::; rm -rf .patched* .untarred* $(LIBNAME)* .checked* .compiled* .configured* .installed* .untarred2* diffs tmp $(UNTARDIR) $(OLDUNTARDIR)
 distclean: clean ; rm -rf Makefile
