*** empty log message ***
git-svn-id: svn://svn.macaulay2.com/Macaulay2/trunk@1556 a8012f80-5f13-0410-8dc0-eb77bd940c0d

diff --git a/M2/configure b/M2/configure
--- a/M2/configure
+++ b/M2/configure
@@ -864,7 +864,8 @@ Optional Features:
   --disable-optimize      disable optimization
   --disable-strip         do not strip the Macaulay 2 binary
   --enable-encap          create an encap package
-  --enable-gc-for-new     use gc instead of builtin_new
+  --enable-gc-for-new     use gc instead of malloc for c++ 'new' and 'delete'
+                          operators
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -4230,9 +4231,9 @@ _ACEOF
 fi
 
 
-echo "$as_me:$LINENO: checking whether sys_errlist herror gnu_get_libc_version is declared" >&5
-echo $ECHO_N "checking whether sys_errlist herror gnu_get_libc_version is declared... $ECHO_C" >&6
-if test "${ac_cv_have_decl_sys_errlist_herror_gnu_get_libc_version+set}" = set; then
+echo "$as_me:$LINENO: checking whether sys_errlist is declared" >&5
+echo $ECHO_N "checking whether sys_errlist is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_sys_errlist+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -4246,8 +4247,8 @@ $ac_includes_default
 int
 main ()
 {
-#ifndef sys_errlist herror gnu_get_libc_version
-  char *p = (char *) sys_errlist herror gnu_get_libc_version;
+#ifndef sys_errlist
+  char *p = (char *) sys_errlist;
 #endif
 
   ;
@@ -4266,27 +4267,153 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_have_decl_sys_errlist_herror_gnu_get_libc_version=yes
+  ac_cv_have_decl_sys_errlist=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_have_decl_sys_errlist_herror_gnu_get_libc_version=no
+ac_cv_have_decl_sys_errlist=no
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
 fi
-echo "$as_me:$LINENO: result: $ac_cv_have_decl_sys_errlist_herror_gnu_get_libc_version" >&5
-echo "${ECHO_T}$ac_cv_have_decl_sys_errlist_herror_gnu_get_libc_version" >&6
-if test $ac_cv_have_decl_sys_errlist_herror_gnu_get_libc_version = yes; then
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_sys_errlist" >&5
+echo "${ECHO_T}$ac_cv_have_decl_sys_errlist" >&6
+if test $ac_cv_have_decl_sys_errlist = yes; then
 
 cat >>confdefs.h <<_ACEOF
-#define HAVE_DECL_SYS_ERRLIST_HERROR_GNU_GET_LIBC_VERSION 1
+#define HAVE_DECL_SYS_ERRLIST 1
 _ACEOF
 
 
 else
   cat >>confdefs.h <<_ACEOF
-#define HAVE_DECL_SYS_ERRLIST_HERROR_GNU_GET_LIBC_VERSION 0
+#define HAVE_DECL_SYS_ERRLIST 0
+_ACEOF
+
+
+fi
+
+
+echo "$as_me:$LINENO: checking whether herror is declared" >&5
+echo $ECHO_N "checking whether herror is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_herror+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+int
+main ()
+{
+#ifndef herror
+  char *p = (char *) herror;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl_herror=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_decl_herror=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_herror" >&5
+echo "${ECHO_T}$ac_cv_have_decl_herror" >&6
+if test $ac_cv_have_decl_herror = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL_HERROR 1
+_ACEOF
+
+
+else
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL_HERROR 0
+_ACEOF
+
+
+fi
+
+
+echo "$as_me:$LINENO: checking whether gnu_get_libc_version is declared" >&5
+echo $ECHO_N "checking whether gnu_get_libc_version is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_gnu_get_libc_version+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+int
+main ()
+{
+#ifndef gnu_get_libc_version
+  char *p = (char *) gnu_get_libc_version;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl_gnu_get_libc_version=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_decl_gnu_get_libc_version=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_gnu_get_libc_version" >&5
+echo "${ECHO_T}$ac_cv_have_decl_gnu_get_libc_version" >&6
+if test $ac_cv_have_decl_gnu_get_libc_version = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL_GNU_GET_LIBC_VERSION 1
+_ACEOF
+
+
+else
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL_GNU_GET_LIBC_VERSION 0
 _ACEOF
 
 
