*** empty log message ***
git-svn-id: svn://svn.macaulay2.com/Macaulay2/trunk@1767 a8012f80-5f13-0410-8dc0-eb77bd940c0d

diff --git a/M2/configure b/M2/configure
--- a/M2/configure
+++ b/M2/configure
@@ -4311,6 +4311,51 @@ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
+echo "$as_me:$LINENO: checking whether readline library is installed" >&5
+echo $ECHO_N "checking whether readline library is installed... $ECHO_C" >&6
+LIBS="-lreadline -lhistory -lcurses $SAVELIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+extern char *readline(const char *);extern void add_history (const char *);
+int
+main ()
+{
+readline;add_history;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6;{ { echo "$as_me:$LINENO: error: missing library: readline" >&5
+echo "$as_me: error: missing library: readline" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
 LIBS="$SAVELIBS"
 
 
