*** empty log message ***
git-svn-id: svn://svn.macaulay2.com/Macaulay2/trunk@3485 a8012f80-5f13-0410-8dc0-eb77bd940c0d

diff --git a/M2/configure b/M2/configure
--- a/M2/configure
+++ b/M2/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CFLAGS LOADLIBES LDLIBS MAKE NODENAME REL ARCH OS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CXX RANLIB ac_ct_RANLIB INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA AWK LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT GCC CXXFLAGS ac_ct_CXX YACC ALLOCA CPP EGREP DUMPDATA PROFILE FACTORY STRIP DEBUG VERBOSE STATIC MEMDEBUG OPTIMIZE ENCAP XCODE ALTIVEC LAPACK M2SUFFIX LAPACKLIBS HAVE_LIBGC_PG HAVE_LIBGMP_PG HAVE_LIBNTL_PG HAVE_LIBCF_PG HAVE_LIBFAC_PG CONFIGURED_FILES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CFLAGS LOADLIBES LDLIBS MAKE INSTALL_INFO NODENAME REL ARCH OS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CXX RANLIB ac_ct_RANLIB INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA AWK LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT GCC CXXFLAGS ac_ct_CXX YACC ALLOCA CPP EGREP DUMPDATA PROFILE FACTORY STRIP DEBUG VERBOSE STATIC MEMDEBUG OPTIMIZE ENCAP XCODE ALTIVEC LAPACK M2SUFFIX LAPACKLIBS HAVE_LIBGC_PG HAVE_LIBGMP_PG HAVE_LIBNTL_PG HAVE_LIBCF_PG HAVE_LIBFAC_PG CONFIGURED_FILES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1371,7 +1371,7 @@ test "$CXXFLAGS"   && echo "   CXXFLAGS=$CXXFLAGS"
 test "$LDFLAGS"    && echo "   LDFLAGS=$LDFLAGS"
 
 if test "$CXX" = gcc
-then echo oops, CXX=gcc, should use CXX=g++
+then echo oops, CXX=gcc, should use CXX=g++ >&2
      exit 1
 fi
 
@@ -1434,6 +1434,58 @@ then echo "yes" >&6
 else echo "`basename $0`: $MAKE: GNU make is required" >&2
      exit 1
 fi
+
+# Extract the first word of "install-info", so it can be a program name with args.
+set dummy install-info; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_INSTALL_INFO+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$INSTALL_INFO"; then
+  ac_cv_prog_INSTALL_INFO="$INSTALL_INFO" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_INSTALL_INFO="yes"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+INSTALL_INFO=$ac_cv_prog_INSTALL_INFO
+if test -n "$INSTALL_INFO"; then
+  echo "$as_me:$LINENO: result: $INSTALL_INFO" >&5
+echo "${ECHO_T}$INSTALL_INFO" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if ! test "$INSTALL_INFO"
+then echo "configure: error: program 'install-info' (from the 'texinfo' package) not found" >&2
+     exit 1
+fi
+install-info --version |
+  egrep '^install-info' |
+  sed -e 's/^.* \([1-9][0-9]*\)\.\([1-9][0-9]*\)/\1 \2/' -e 's/^i.*//' |
+  if read major minor
+  then min=4
+       if test "$major" -lt "$min"
+       then echo "Macaulay2 requires 'install-info' (from the 'texinfo' package) at least version $min" >&2
+	    false
+       fi
+  else echo "configure: error: program 'install-info' version number not recognized" >&2
+       false
+  fi || exit 1
 
 NODENAME="`uname -n`"
 
@@ -6638,6 +6690,7 @@ s,@CFLAGS@,$CFLAGS,;t t
 s,@LOADLIBES@,$LOADLIBES,;t t
 s,@LDLIBS@,$LDLIBS,;t t
 s,@MAKE@,$MAKE,;t t
+s,@INSTALL_INFO@,$INSTALL_INFO,;t t
 s,@NODENAME@,$NODENAME,;t t
 s,@REL@,$REL,;t t
 s,@ARCH@,$ARCH,;t t
