update debian stuff
git-svn-id: svn://svn.macaulay2.com/Macaulay2/trunk/M2@4621 a8012f80-5f13-0410-8dc0-eb77bd940c0d

diff --git a/debian/postrm.in b/debian/postrm.in
--- a/debian/postrm.in
+++ b/debian/postrm.in
@@ -1,9 +1,24 @@
 #! /bin/sh
+
 set -e
+
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
+# for details, see /usr/share/doc/packaging-manual/
+
 case "$1" in
-    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+        ;;
+    purge)
         ;;
     *)
-	echo "postrm called with unknown argument \`$1'" >&2
-	;;
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
 esac
