git-svn-id: svn://svn.macaulay2.com/Macaulay2/trunk@4131 a8012f80-5f13-0410-8dc0-eb77bd940c0d

diff --git a/M2/arch/MacOSX/setup b/M2/arch/MacOSX/setup
--- a/M2/arch/MacOSX/setup
+++ b/M2/arch/MacOSX/setup
@@ -1,10 +1,16 @@
 #! /bin/bash
 M2PATH=`pwd`
+
+if ! [ -f share/emacs/site-lisp/M2.el ]
+then echo "--error: file ./share/emacs/site-lisp/M2.el not found, please run $0 from the directory it's in" >&2
+     exit 1
+fi
+
 cat >>~/.profile <<STUFF
 ### Macaulay2 ###
   export PATH=$M2PATH/bin:\$PATH
-  export MANPATH=$M2PATH/share/man:$M2PATH/man:\$MANPATH
-  export INFOPATH=$M2PATH/share/info:$M2PATH/info:\$INFOPATH
+  export MANPATH=$M2PATH/share/man:\$MANPATH
+  export INFOPATH=$M2PATH/info:\$INFOPATH
 ### end Macaulay2 ###
 STUFF
 
