start signing and notarizing our code for Mac OS X

diff --git a/M2/distributions/dmg/Makefile.in b/M2/distributions/dmg/Makefile.in
--- a/M2/distributions/dmg/Makefile.in
+++ b/M2/distributions/dmg/Makefile.in
@@ -14,13 +14,15 @@ T=@TAR@ --create --mode=a+rX,og-ws --exclude-from=@srcdir@/../tar-exclusions --f
 ../../$(PKG_DMG) : Makefile always file_preparation library_preparation top-directory-preparation
 	rm -f "$@"
 ifeq ($(SIGN),yes)
-	@for i in files/@package@/@tail_bindir@/* files/@package@/@tail_programsdir@/* files/@package@/@tail_libdir@/*dylib ;						\
-	do (set -x ; codesign --timestamp -o runtime -v -s "Developer ID Application: Daniel Grayson (C7RV9R283Q)" "$$i" 2>error.log) ;	\
-	   if test $$? != 0 ;														\
-	   then cat error.log ;														\
-	        ! grep --silent "is already signed" error.log && exit 1 ;								\
-	   fi ;																\
-	done
+	@for i in files/@package@/@tail_bindir@/* files/@package@/@tail_programsdir@/* files/@package@/@tail_libdir@/*dylib ;			\
+	 do if test -f "$$i" ;															\
+	    then (set -x ; codesign --timestamp -o runtime -v -s "Developer ID Application: Daniel Grayson (C7RV9R283Q)" "$$i" 2>error.log) ;	\
+		 if test $$? != 0 ;														\
+		 then cat error.log ;														\
+		      ! grep --silent "is already signed" error.log && exit 1 ;									\
+		 fi ;																\
+	    fi;																	\
+	 done
 endif
 	@echo "warning: sometimes the following command gives a mystical error message about '(ipc/send) invalid destination port' ... "
 	hdiutil create -srcfolder files -volname "@package@-@ARCH@-@OS@-@REL@" "$@"
@@ -28,7 +30,7 @@ ifeq ($(SIGN),yes)
 	codesign --timestamp -o runtime -v -s "Developer ID Application: Daniel Grayson (C7RV9R283Q)" "$@"
 	xcrun altool --notarize-app --primary-bundle-id "notarize-bar.dmg" --username danielrichardgrayson@gmail.com --password "@keychain:AC_PASSWORD" --file "$@"
 	: : : : now wait for confirmation of success of notarization to arrive by email, then press EOF : : : : : : : : : : : :
-	cat
+	read
 	stapler staple "$@"
 endif
 
@@ -54,30 +56,35 @@ file_preparation: always
 # Read about all that with "man dyld".
 library_preparation: file_preparation
 	$(MKDIR_P) files/@package@/@tail_libdir@
-	(																\
+
+	( set -e;															\
 	  for i in files/@package@/@tail_bindir@/* ;											\
 	  do if [ -f $$i -a -x $$i -a ! -h $$i ] ;											\
 	     then otool -L $$i | grep '^\t' | grep -v '^[[:space:]]*\(/usr/lib/\|/System/Library/\)'					\
 		  | sed 's/^[[:space:]]*\(.*\) (compatibility version .*/\1/'								\
 		  | while read f;													\
-		    do (b=`basename $$f` ; set -xe ; install_name_tool -change $$f @executable_path/../lib/$$b $$i ) || exit 1 ; 	\
-		       echo $$f ; 													\
+		    do echo "library preparation: error *** : file $$i uses dynamic library $$f" >&2;					\
+		       exit 1;														\
 		       done ;														\
 	     fi ;															\
-	  done ;															\
+	  done &&															\
 	  for i in files/@package@/@tail_programsdir@/* ;										\
 	  do if [ -f $$i -a -x $$i -a ! -h $$i ] ;											\
 	     then otool -L $$i | grep '^\t' | grep -v '^[[:space:]]*\(/usr/lib/\|/System/Library/\)'					\
 		  | sed 's/^[[:space:]]*\(.*\) (compatibility version .*/\1/'								\
 		  | while read f;													\
-		    do (b=`basename $$f` ; set -xe ; install_name_tool -change $$f @executable_path/../../../lib/$$b $$i ) || exit 1 ; 	\
-		       echo $$f ; 													\
-		       done ;														\
+		    do echo "library preparation: error *** : file $$i uses dynamic library $$f" >&2;					\
+		       exit 1;														\
+		    done ;														\
 	     fi ;															\
 	  done																\
-	) | sort															\
-	  | uniq															\
+	) >libraries.tmp ;
+
+	<libraries.tmp												\
+	  | sort												\
+	  | uniq												\
 	  | while read f; do ls -l $$f ; (set -x ; @INSTALL_PROGRAM@ $$f files/@package@/@tail_libdir@ ) ; done
+
 	for i in files/@package@/@tail_libdir@/* ;							\
 	do if [ -f $$i -a -x $$i -a ! -h $$i ] ;							\
 	   then otool -L $$i | grep '^\t' | grep -v '^[[:space:]]*\(/usr/lib/\|/System/Library/\)'	\
@@ -85,15 +92,16 @@ library_preparation: file_preparation
 		| while read f;										\
 		  do (bf=`basename $$f` ;								\
 		      bi=`basename $$i` ;								\
-		      set -x ; \
+		      set -x ;										\
 		      if [ $$bf = $$bi ] ;								\
 		      then set -xe ; install_name_tool -id $$bi $$i ;					\
-		      else set -xe ; install_name_tool -change $$f @loader_path/$$bf $$i ; 		\
+		      else set -xe ; install_name_tool -change $$f @loader_path/$$bf $$i ;		\
 		      fi ) || exit 1 ;									\
 		     echo $$f ;										\
 		     done ;										\
 	   fi ;												\
 	done
+
 	: dynamic libraries to be distributed:
 	cd files/@package@/@tail_libdir@ && for i in * ; do if [ -f $$i ] ; then (echo "-- $$i" ; set -x ; ls -l $$i ; otool -L $$i ) ; fi ; done
 
