when making a dmg file: give an error if any binaries to be distributed depend on non-system dynamic libraries

diff --git a/M2/distributions/dmg/Makefile.in b/M2/distributions/dmg/Makefile.in
--- a/M2/distributions/dmg/Makefile.in
+++ b/M2/distributions/dmg/Makefile.in
@@ -4,11 +4,16 @@ include ../../include/config.Makefile
 VPATH = @srcdir@
 DEPENDS = yes
 PKG_DMG = @package@-@ARCH@-@OS@-@REL@.dmg
+
+# -rpath is broken under Mac OS X, since each dynamic library specifies whether to use it, and the gcc libraries we link with don't use it:
+DISTRIBUTE_BINARY_SWITCH = echo 'error: *** program linked with non-system dynamic library, perhaps configure with --enable-static-gcc-libs' >&2 ; exit 1
+
 all: dmg tidy
 dmg: ../../$(PKG_DMG)
 T=@TAR@ --create --mode=a+rX,og-ws --exclude-from=@srcdir@/../tar-exclusions --file=-
 ../../$(PKG_DMG) : Makefile always file_preparation library_preparation
 	rm -f "$@"
+	@echo "warning: sometimes the following command gives a mystical error message about '(ipc/send) invalid destination port' ... "
 	hdiutil create -srcfolder files -volname "@package@-@ARCH@-@OS@-@REL@" "$@"
 file_preparation: always
 	rm -rf files
@@ -21,13 +26,13 @@ library_preparation: file_preparation
 	$(MKDIR_P) files/@package@/@tail_libdir@
 	for i in files/@package@/@tail_bindir@/* files/@package@/@tail_programsdir@/* ;\
 	 do if [ -f $$i -a -x $$i ] ;\
-	    then echo $$i >&2 ;\
-		 otool -L $$i | grep '^\t' | grep -v '^[[:space:]]*\(/usr/lib/\|/System/Library/\)' \
+	    then otool -L $$i | grep '^\t' | grep -v '^[[:space:]]*\(/usr/lib/\|/System/Library/\)' \
 		 | sed 's/^[[:space:]]*\(.*\) (compatibility version .*/\1/' ;\
 	    fi ;\
 	 done | sort \
 	      | uniq \
-	      | while read f ; do ls -l $$f ; @INSTALL_PROGRAM@ $$f files/@package@/@tail_libdir@ ; done
+	      | while read f; do ls -l $$f ; $(DISTRIBUTE_BINARY_SWITCH); @INSTALL_PROGRAM@ $$f files/@package@/@tail_libdir@ ; done
+	: dynamic libraries to be distributed:
 	ls -l files/@package@/@tail_libdir@
 tidy:; rm -rf files
 clean:: tidy; rm -f "../../$(PKG_DMG)"
